<a href="https://colab.research.google.com/github/sushant758/MATHS-FOR-ML-/blob/main/day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix Multiplication

1. Matrix multiplication understanding.
2. matmul() write with nested loops.
3. Two matrices multiplication.
4. verify with np.dot().
5. Time compare

In [ ]:
import numpy as np
import time

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

In [ ]:
print(A.shape)

(2, 3)


In [ ]:
print(B.shape)

(3, 2)


In [ ]:
rows_A = A.shape[0]
cols_A = A.shape[1]

print(rows_A)
print(cols_A)

2
3


In [ ]:
rows_B = B.shape[0]
cols_B = B.shape[1]

print(rows_B)
print(cols_B)

3
2


In [ ]:
if cols_A != rows_B:
    raise ValueError("Matrix multiplication not possible")

In [ ]:
result = np.zeros((rows_A, cols_B))

In [ ]:
for i in range(rows_A):
  for j in range(cols_B):
    total = 0
    for k in range(cols_A):
      A[i][k]
      B[k][j]
      total += A[i][k] * B[k][j]
      result[i][j] = total

In [ ]:
result

array([[ 58.,  64.],
       [139., 154.]])

In [ ]:
# Result[0][0]
# (1×7)+(2×9)+(3×11)
# 7+18+33=58

# Result[0][1]
# (1×8)+(2×10)+(3×12)
# 8+20+36=64

# Result[1][0]
# (4×7)+(5×9)+(6×11)
# 28+45+66=139

# Result[1][1]
# (4×8)+(5×10)+(6×12)
# 32+50+72=154

In [ ]:
numpy_result = np.dot(A,B)
numpy_result

array([[ 58,  64],
       [139, 154]])

# verify with np.dot().

In [ ]:
numpy_result = np.dot(A, B)

print("My Result:")
print(result)

print("Numpy Result:")
print(numpy_result)


print("\nEqual?")
print(np.array_equal(result, numpy_result))

My Result:
[[ 58.  64.]
 [139. 154.]]
Numpy Result:
[[ 58  64]
 [139 154]]

Equal?
True


# Speed Comparison

In [ ]:
A = np.random.rand(50, 50)
B = np.random.rand(50, 50)

In [ ]:
print(A)

[[0.74626876 0.31239097 0.76252995 ... 0.38237534 0.4319594  0.9300328 ]
 [0.20411927 0.62329876 0.15922561 ... 0.23409394 0.07543038 0.68143853]
 [0.24248775 0.49025183 0.36265413 ... 0.93920641 0.42953234 0.34894222]
 ...
 [0.94819852 0.34933927 0.15133153 ... 0.69765082 0.55620411 0.72411328]
 [0.75212638 0.79134405 0.72800591 ... 0.86935782 0.39027584 0.71233096]
 [0.46413788 0.92526967 0.94218296 ... 0.80228953 0.27572619 0.62476971]]


In [ ]:
print(B)

[[0.12669084 0.08678266 0.34668343 ... 0.03572227 0.93392939 0.13153144]
 [0.29032249 0.25030085 0.52460558 ... 0.78216422 0.12733105 0.05732196]
 [0.42574225 0.06000767 0.75799739 ... 0.65170028 0.40843032 0.84074281]
 ...
 [0.88477069 0.81253292 0.24031596 ... 0.46430407 0.12130187 0.74212739]
 [0.51418828 0.65364315 0.0529568  ... 0.56871286 0.41007779 0.09988763]
 [0.65437185 0.70088635 0.83693266 ... 0.48088184 0.33550073 0.68113863]]


In [ ]:
def matmul(A, B):

    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape

    if cols_A != rows_B:
        raise ValueError("Matrix multiplication not possible")

    result = np.zeros((rows_A, cols_B))

    for i in range(rows_A):
        for j in range(cols_B):

            total = 0

            for k in range(cols_A):
                total += A[i][k] * B[k][j]

            result[i][j] = total

    return result

In [ ]:
start = time.perf_counter()

my_result = matmul(A, B)

end = time.perf_counter()

print(f"Custom Time: {end - start:.6f} seconds")

Custom Time: 0.093506 seconds


In [ ]:
import time

matmul_start = time.perf_counter()

my_result = matmul(A, B)

matmul_end = time.perf_counter()

print("Result Shape:", my_result.shape)
print(f"Custom Time: {matmul_end - matmul_start:.6f} seconds")

Result Shape: (50, 50)
Custom Time: 0.098708 seconds


In [ ]:
numpy_start = time.perf_counter()

numpy_result = np.dot(A, B)

numpy_end = time.perf_counter()

print("NumPy Time:", numpy_end - numpy_start)

NumPy Time: 0.000914843000032306


In [ ]:
extra_time = (matmul_end - matmul_start) - (numpy_end - numpy_start)
print("Extra Time:", extra_time)

Extra Time: 0.09779268399995544
