<a href="https://colab.research.google.com/github/sushant758/MATHS-FOR-ML-/blob/main/day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 5 — Identity & Inverse Matrix

✅ create Identity matrix

✅ Verify A×I=A

✅ Determinant understand

✅ 2×2 inverse by hand find

✅ NumPy verify

✅ 3×3 inverse by hand find

✅ NumPy  verify

✅ 3–4 lines write geometric meaning.

✅ 2–3 lines ML relation write

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
matrix_1 = np.identity(3)

In [ ]:
matrix_1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A = np.random.rand(3,3)

In [ ]:
A

array([[0.62730245, 0.57622442, 0.38842299],
       [0.698239  , 0.31483266, 0.85309044],
       [0.97675701, 0.0783508 , 0.18221486]])

In [ ]:
identity_matrix = np.dot(A,matrix_1)

In [ ]:
identity_matrix

array([[0.62730245, 0.57622442, 0.38842299],
       [0.698239  , 0.31483266, 0.85309044],
       [0.97675701, 0.0783508 , 0.18221486]])

In [ ]:
determinant_A = np.linalg.det(A)

In [ ]:
determinant_A

np.float64(0.30269446182063736)

# 2×2 inverse by hand find

In [ ]:
B = np.random.rand(2,2)
a = B[0][0]
b = B[0][1]
c = B[1][0]
d = B[1][1]

In [ ]:
B

array([[0.89009203, 0.55954381],
       [0.5925997 , 0.55479531]])

In [ ]:
determinant = (a*d) - (b*c)

if determinant == 0:
  raise ValueError('Matrix is singular and cannot be inverted')

inv_matrix = [
     [ d / determinant, -b / determinant],
     [-c / determinant,  a / determinant]
]

inv_matrix

[[np.float64(3.4197356280786892), np.float64(-3.449005185600705)],
 [np.float64(-3.6527603596300575), np.float64(5.486490958042778)]]

In [ ]:
# Verify with Numpy

det_numpy = np.linalg.det(B)

adj_matrix_numpy = np.array([
    [B[1,1], -B[0,1]],
    [-B[1,0], B[0,0]]
])

inv_matrix_numpy = adj_matrix_numpy / det_numpy

inv_matrix_numpy

array([[ 3.41973563, -3.44900519],
       [-3.65276036,  5.48649096]])

# 3×3 inverse by hand find

In [ ]:
# Random 3x3 matrix
m = np.random.rand(3,3)

print("Original Matrix:\n")
print(m)

a = m[0,0]
b = m[0,1]
c = m[0,2]

d = m[1,0]
e = m[1,1]
f = m[1,2]

g = m[2,0]
h = m[2,1]
i = m[2,2]

Original Matrix:

[[0.36034345 0.98824955 0.05298764]
 [0.13243125 0.06654156 0.84168074]
 [0.30430175 0.64256878 0.58771268]]


In [ ]:
# Determinant
det = (
    a*(e*i - f*h)
    - b*(d*i - f*g)
    + c*(d*h - e*g)
)

print("\nDeterminant:")
print(det)

if np.isclose(det, 0):
    raise ValueError("Matrix is singular and cannot be inverted.")

# Cofactor Matrix
cofactor = np.array([
    [ (e*i - f*h), -(d*i - f*g),  (d*h - e*g)],
    [-(b*i - c*h),  (a*i - c*g), -(a*h - b*g)],
    [ (b*f - c*e), -(a*f - c*d),  (a*e - b*d)]
])

print("\nCofactor Matrix:")
print(cofactor)

# Adjugate = Transpose of Cofactor
adjugate = cofactor.T

print("\nAdjugate Matrix:")
print(adjugate)

# Manual Inverse
inv_matrix = adjugate / det

print("\nManual Inverse:")
print(inv_matrix)


Determinant:
-0.001160794467054848

Cofactor Matrix:
[[-0.50173045  0.1782934   0.06484748]
 [-0.54675859  0.19565418  0.06918062]
 [ 0.82826474 -0.29627692 -0.10689731]]

Adjugate Matrix:
[[-0.50173045 -0.54675859  0.82826474]
 [ 0.1782934   0.19565418 -0.29627692]
 [ 0.06484748  0.06918062 -0.10689731]]

Manual Inverse:
[[ 432.23022471  471.02101836 -713.5326363 ]
 [-153.59601043 -168.55195956  255.23633051]
 [ -55.86473655  -59.59764993   92.08978531]]


In [ ]:

# NumPy Verification
numpy_inverse = np.linalg.inv(m)

print("\nNumPy Inverse:")
print(numpy_inverse)

# Check if both are equal
print("\nAre they equal?")
print(np.allclose(inv_matrix, numpy_inverse))


NumPy Inverse:
[[ 432.23022471  471.02101836 -713.5326363 ]
 [-153.59601043 -168.55195956  255.23633051]
 [ -55.86473655  -59.59764993   92.08978531]]

Are they equal?
True


Geometric Meaning of an Inverse Matrix

The inverse matrix represents the reverse of a transformation. If a matrix stretches, rotates, or shears a vector, its inverse undoes that transformation and restores the original vector. Multiplying a matrix by its inverse results in the identity matrix, which leaves vectors unchanged.

ML Relation

In Linear Regression, the Normal Equation uses a matrix inverse to directly compute the optimal model weights. The term (X
T
X)
−1
 is used to solve for the coefficients without iterative training. Therefore, understanding matrix inverses is important for the mathematical foundation of machine lear