<a href="https://colab.research.google.com/github/sushant758/MATHS-FOR-ML-/blob/main/day7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# Determinant & Rank

In [ ]:
# For 2×2:

# A=[a b
#   c d]

# det(A)=ad−bc

# If det(A)=0 then ,
# Matrix Singular
# Matrix Inverse Does Not Exist

In [ ]:
# BY hand

A = np.array([
    [4, 2],
    [3, 1]
])

In [ ]:
det_A = ((4 * 1) - (2 * 3))
det_A

-2

In [ ]:
# verify with numpy

numpy_det_A = np.linalg.det(A)
numpy_det_A

np.float64(-2.0)

# Part 2: 3×3 Determinant

In [ ]:
B = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])

In [ ]:
det_B = ( 1*(((1*0) -(6*4)) - 2*((0*0) - (5*4)) + 3*((0*6) - (5*1))) )
det_B

1

In [ ]:
numpy_det_B = np.linalg.det(B)
numpy_det_B

np.float64(0.9999999999999964)

In [ ]:
# conclusion = The determinant tells us whether a matrix can be inverted and how much it stretches or shrinks space.

# Part 3: Rank

The rank indicates:

How much independent information a matrix contains.

In [ ]:
A = np.array([
    [1, 2],
    [2, 4]
])

In [ ]:
# here Row2 = 2 × Row1., here second row is giving a new information.  . Rank = 1

In [ ]:
np.linalg.matrix_rank(A)

np.int64(1)

### 3 by 3 matrix

In [ ]:
X = np.array([
    [1, 2],
    [2, 4],
    [3, 6],
    [4, 8]
])

In [ ]:
# Column2 = 2 × Column1.

In [ ]:
rank_X = np.linalg.matrix_rank(X)
rank_X

np.int64(1)

# ML Relation

In [ ]:
# Suppose:
#        experience
#        salary
#
#  And = salary = 10000 × experience

# Then:

# Features are redundant

In [ ]:
# What does determinant = 0 mean?

# Matrix is singular and non-invertible.

In [ ]:
# What does rank represent?

# Number of linearly independent rows or columns.

# Industry-Level Extension

In [ ]:
feature_1 = np.random.rand(100)
feature_1

array([0.52904734, 0.33977504, 0.10512299, 0.9299677 , 0.46466529,
       0.87236185, 0.12090115, 0.47310978, 0.66539133, 0.68004053,
       0.76128889, 0.548691  , 0.01134788, 0.36124902, 0.93140866,
       0.3589385 , 0.96990064, 0.58881515, 0.26118769, 0.66000259,
       0.50230343, 0.83163317, 0.82226469, 0.50594257, 0.31735134,
       0.73953464, 0.81807945, 0.81622757, 0.70932488, 0.46678568,
       0.26035237, 0.16993052, 0.83849491, 0.77666249, 0.01256484,
       0.79862217, 0.79055872, 0.13484945, 0.24293372, 0.33125055,
       0.912     , 0.82377994, 0.39345125, 0.23658175, 0.01557158,
       0.02845638, 0.22304258, 0.5276791 , 0.36040634, 0.78612742,
       0.55355843, 0.96662111, 0.30107714, 0.63805124, 0.2608952 ,
       0.63152794, 0.90954278, 0.98642725, 0.67856517, 0.20221667,
       0.56556802, 0.75102192, 0.97746804, 0.10154997, 0.20423468,
       0.89206658, 0.05119077, 0.85226992, 0.62369916, 0.12876744,
       0.32802599, 0.92235597, 0.32996155, 0.70312151, 0.86918

In [ ]:
feature_2 = 2 * feature_1

In [ ]:
X = np.column_stack([feature_1, feature_2])

In [ ]:
X

array([[0.52904734, 1.05809467],
       [0.33977504, 0.67955008],
       [0.10512299, 0.21024598],
       [0.9299677 , 1.85993541],
       [0.46466529, 0.92933058],
       [0.87236185, 1.74472369],
       [0.12090115, 0.24180231],
       [0.47310978, 0.94621955],
       [0.66539133, 1.33078265],
       [0.68004053, 1.36008105],
       [0.76128889, 1.52257778],
       [0.548691  , 1.09738201],
       [0.01134788, 0.02269575],
       [0.36124902, 0.72249804],
       [0.93140866, 1.86281733],
       [0.3589385 , 0.71787699],
       [0.96990064, 1.93980127],
       [0.58881515, 1.17763029],
       [0.26118769, 0.52237538],
       [0.66000259, 1.32000519],
       [0.50230343, 1.00460685],
       [0.83163317, 1.66326633],
       [0.82226469, 1.64452937],
       [0.50594257, 1.01188514],
       [0.31735134, 0.63470267],
       [0.73953464, 1.47906928],
       [0.81807945, 1.6361589 ],
       [0.81622757, 1.63245514],
       [0.70932488, 1.41864977],
       [0.46678568, 0.93357136],
       [0.

In [ ]:
# check rank
rank_X = np.linalg.matrix_rank(X)
rank_X

np.int64(1)

In [ ]:
# check determinant


XTX = X.T @ X
print(XTX.shape)
np.linalg.det(XTX)

(2, 2)


np.float64(0.0)

In [ ]:
# check inverse
pseudo_inverse = np.linalg.pinv(XTX)
pseudo_inverse

array([[0.00105729, 0.00211458],
       [0.00211458, 0.00422917]])