<a href="https://colab.research.google.com/github/sushant758/MATHS-FOR-ML-/blob/main/day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Eigenvalues & Eigenvectors


In [ ]:
import numpy as np
import pandas as pd

Eigenvector :

A direction that remains unchanged after a transformation.

or

An eigenvector is a special vector whose direction remains unchanged after a matrix transformation.

Eigenvalue:

The amount by which that direction is stretched or compressed.

or

An eigenvalue tells how much an eigenvector is stretched or shrunk during the transformation.

# Assignment Part 1

In [ ]:
A = np.array([
    [2, 0],
    [0, 3]
])


print(A)

[[2 0]
 [0 3]]


In [ ]:
# By Hand
# Av=λv

# Where:
# A = Matrix
# v = Eigenvector
# λ = Eigenvalue


# What is happening?
# We are looking for special vectors whose direction does not change after the matrix transformation

# Note:
# Eigenvectors keep their direction after transformation;
#   eigenvalues tell how much they are stretched or compressed.

In [ ]:
# Step 2: Move Everything to One Side

# Mathematics = Av−λv=0
#             = (A−λI)v=0

In [ ]:
I = np.eye(2)

print(I)

[[1. 0.]
 [0. 1.]]


In [ ]:
# Note

# We introduce the identity matrix so that λ can be written in matrix form and subtracted from A.

In [ ]:
print("""
A - λI =

[2-λ   0  ]
[ 0   3-λ ]
""")


A - λI =

[2-λ   0  ]
[ 0   3-λ ]



In [ ]:
print("det(A - λI) = 0")

det(A - λI) = 0


In [ ]:
print("(2 - λ)(3 - λ) = 0")

(2 - λ)(3 - λ) = 0


In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

Eigenvalues:
[2. 3.]


In [ ]:
import numpy as np

A = np.array([
    [2, 0],
    [0, 3]
])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[2. 3.]

Eigenvectors:
[[1. 0.]
 [0. 1.]]
