<a href="https://colab.research.google.com/github/sushant758/MATHS-FOR-ML-/blob/main/day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PCA From Scratch

In [ ]:
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd


In [ ]:
iris = load_iris()
X = iris.data

In [ ]:
print(X.shape)

(150, 4)


In [ ]:
X_mean = np.mean(X, axis=0)

In [ ]:
X_centered = X - X_mean

In [ ]:
print(X_mean)

[5.84333333 3.05733333 3.758      1.19933333]


In [ ]:
cov_matrix = np.cov(X_centered.T)

In [ ]:
print(cov_matrix.shape)

(4, 4)


In [ ]:
print(cov_matrix)

[[ 0.68569351 -0.042434    1.27431544  0.51627069]
 [-0.042434    0.18997942 -0.32965638 -0.12163937]
 [ 1.27431544 -0.32965638  3.11627785  1.2956094 ]
 [ 0.51627069 -0.12163937  1.2956094   0.58100626]]


In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

In [ ]:
print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[4.22824171 0.24267075 0.0782095  0.02383509]

Eigenvectors:
[[ 0.36138659 -0.65658877 -0.58202985  0.31548719]
 [-0.08452251 -0.73016143  0.59791083 -0.3197231 ]
 [ 0.85667061  0.17337266  0.07623608 -0.47983899]
 [ 0.3582892   0.07548102  0.54583143  0.75365743]]


In [ ]:
sorted_indices = np.argsort(eigenvalues)[::-1]

In [ ]:
eigenvalues = eigenvalues[sorted_indices]

In [ ]:
eigenvectors = eigenvectors[:, sorted_indices]

In [ ]:
print(eigenvalues)

[4.22824171 0.24267075 0.0782095  0.02383509]


In [ ]:
k = 2

In [ ]:
principal_components = eigenvectors[:, :k]

In [ ]:
print(principal_components.shape)

(4, 2)


In [ ]:
X_pca = X_centered @ principal_components

In [ ]:
print(X_pca.shape)

(150, 2)


In [ ]:
explained_variance_ratio = eigenvalues / np.sum(eigenvalues)

In [ ]:
print(explained_variance_ratio)

[0.92461872 0.05306648 0.01710261 0.00521218]


In [ ]:
variance_retained = np.sum(explained_variance_ratio[:2])

In [ ]:
print("Variance Retained:", variance_retained)

Variance Retained: 0.9776852063187949


# Compare with sklearn PCA.

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components=2)

In [ ]:
X_sklearn = pca.fit_transform(X)

In [ ]:
print(X_sklearn.shape)

(150, 2)
