<a href="https://colab.research.google.com/github/sushant758/MATHS-FOR-ML-/blob/main/operations_on_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# operations on Matrices using Numpy

In [23]:
import numpy as np
import time

In [24]:
# test and compare performance of numpy vs plain ppython loop - vector addition.

n=10000000
a=[1]*n
b=[2]*n

start = time.time()

c=[0]*n


for i in range(n):
  c[i] = a[i] + b[i]

end = time.time()

print(end-start)

2.213411569595337


In [25]:
# now performing the same task using numpy
start = time.time()

a_np = np.arange(n)
b_np = np.arange(n)

c_np = a_np + b_np  #

end = time.time()
print(end-start)

0.0791170597076416


In [26]:
1.6246581077575684 / 0.08672761917114258

18.732880289859853

In [27]:
# demo Numpy built-ins vs Python loop


In [28]:
# create 2 metrices using numpy array
A = np.array([[1,2,3],[0,1,0],[0,0,1]]) # matrix A
B = np.array([[0,1,0],[1,0,0],[1,2,1]]) # matrix B

# vectorization is being used internally here,bcz it is converted into
# numpy array.

In [29]:
A.shape

(3, 3)

In [30]:
A

array([[1, 2, 3],
       [0, 1, 0],
       [0, 0, 1]])

In [31]:
B.shape

(3, 3)

In [32]:
B

array([[0, 1, 0],
       [1, 0, 0],
       [1, 2, 1]])

In [33]:
# find sum of the metrices
print(A+B)

[[1 3 3]
 [1 1 0]
 [1 2 2]]


In [34]:
# find differnce of the metrices
print(A-B)

[[ 1  1  3]
 [-1  1  0]
 [-1 -2  0]]


In [35]:
# product
print(A@B)

[[5 7 3]
 [1 0 0]
 [1 2 1]]


In [22]:
print(np.matmul(A,B))

[[5 7 3]
 [1 0 0]
 [1 2 1]]


In [37]:
# transpose
print(A.T)

[[1 0 0]
 [2 1 0]
 [3 0 1]]


In [38]:
print(np.transpose(A))

[[1 0 0]
 [2 1 0]
 [3 0 1]]


In [39]:
# determinant
print(np.linalg.det(A))

1.0


In [40]:
print(np.linalg.det(B))

-1.0


In [41]:
# inverse
print(np.linalg.inv(A))

[[ 1. -2. -3.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [42]:
print(np.linalg.inv(B))

[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [-2. -1.  1.]]


In [43]:
# Trace Find

print(np.linalg.trace(A))

3


In [44]:
print(np.linalg.trace(B))

1


In [45]:
# rank of a matrix
print(np.linalg.matrix_rank(A))

3


In [46]:
print(np.linalg.matrix_rank(B))

3


In [47]:
# eigens value and eigen vector of a matrix

print(np.linalg.eig(A))

EigResult(eigenvalues=array([1., 1., 1.]), eigenvectors=array([[ 1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 0.00000000e+00,  1.11022302e-16,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  7.40148683e-17]]))
